select * from customer limit 5;
--total revenue generated by both male and female
select gender, sum(purchase_amount) as revenue from customer
group by gender;

-- which customers used discount but ended up spending more than purchase amount
SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' 
and purchase_amount >= 59.76;

--Which are highest top products with the highest average reveiw rate
select item_purchased, round(avg(review_rating)::numeric,2) as top_rated from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Compare average purchase amount between Standard and Express shipping
select shipping_type, round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- Do subcribed customers spend more?Compare average spending and total revenue 
-- between subscibed and non-subscribed customers
select subscription_status, count(customer_id) as total_customers,
round(avg(purchase_amount),2) as average_spending, round(sum(purchase_amount),2)
as total_revenue from customer group by subscription_status order by total_revenue,
average_spending desc

-- Which 5 products have the highest percentageof purchases with discount applied
select item_purchased, round(100.0*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2)
 as discounted_rate from customer
 group by item_purchased order by discounted_rate desc

 -- Segement customers into new, returning and loyal based on their total number of previous purchases
-- and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases =1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type group by customer_segment

-- What are the top 3 most purchased products within each category
with item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category,item_purchased, total_orders from item_counts
where item_rank <= 3

-- Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers
from customer where previous_purchases > 5
group by subscription_status

--What is the revenue contributiion of each age group
select age_group, sum(purchase_amount) as total_rev from customer
group by age_group order by total_rev asc

--total number of customers
select count(customer_id) as total_customers from customer